wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679909476.360753
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.14.0
      8:
      - 5
attn_dropout:
  desc: null
  value: 0.32604932309962176
batch_size:
  desc: null
  value: 32
d_model:
  desc: null
  value: 32
depth:
  desc: null
  value: 3
dim_ff:
  desc: null
  value: 256
heads:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.0004758593864328802
num_epochs:
  desc: null
  value: 100
weight_decay:
  desc: null
  value: 0.0003041880996307499
