wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679911665.700389
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.14.0
      8:
      - 5
attn_dropout:
  desc: null
  value: 0.030358321050233283
batch_size:
  desc: null
  value: 32
d_model:
  desc: null
  value: 64
depth:
  desc: null
  value: 2
dim_ff:
  desc: null
  value: 256
heads:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.006304270878718138
num_epochs:
  desc: null
  value: 80
weight_decay:
  desc: null
  value: 8.95068260019186e-05
