wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679687858.491529
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.16129545100683257
hidden_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.0015544518573365783
num_epochs:
  desc: null
  value: 20
num_layers:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0.0007459937836062715
