wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679912589.123553
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.14.0
      8:
      - 5
attn_dropout:
  desc: null
  value: 0.0017337022277723602
batch_size:
  desc: null
  value: 32
d_model:
  desc: null
  value: 16
depth:
  desc: null
  value: 1
dim_ff:
  desc: null
  value: 128
heads:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.007675934726047863
num_epochs:
  desc: null
  value: 60
weight_decay:
  desc: null
  value: 0.0001845389690521079
