wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679686844.039124
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.21708881117989096
hidden_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.002842724679398946
num_epochs:
  desc: null
  value: 70
num_layers:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.00014921634213925129
