wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679693576.045735
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.10
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.36958174119290393
hidden_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0034620733407131825
num_epochs:
  desc: null
  value: 10
num_layers:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0.0009278620452561352
